var QUESTIONS={
  en:[
    "What color are aliens?",
    "Would you like to go back in time or go to the future?",
    "Who did you want to be when you were a teenager?",
    "What is the best piece of advice you've ever received?",
    "What was the worst job you ever had?",
    "What is one thing we don't know about you?",
    "If you could live anywhere in the world for a year, where would it be?",
    "Would you rather be the funniest or smartest person in the room?",
    "Would you rather visit a volcano or a rainforest?",
    "Describe your dream holiday if money was no limit.",
    "When you were a child, what was your biggest dream?",
    "What talent would you most like to grow and develop?",
    "What activities do you dream of trying someday?",
    "How do you like to dress (smart, relaxed, sweatpants and flip-flops)?",
    "You have one extra hour a day, you can do anything, what would you do?",
    "What “old person” things do you do?",
    "If you could speak another language, what would it be?",
    "Do you have a bucket list? Name one thing on your bucket list.",
    "What is something new or interesting that you've learned recently?",
    "Is there any topic lately that you would like to be mentored on?",
    "If you were reincarnated as an animal, what would you choose and why?",
    "When was the last time you did something for the first time?",
    "Have you ever experienced a culture shock? Where was it and what happened?",
    "Have you learned any useful productivity hacks recently?",
    "What's an adventurous thing you've done or want to do?",
    "Which do you prefer, oceans or mountains? Why?",
    "What scientific discoveries would you like to live to see?",
    "Would your younger self be proud of who you are today?",
    "If you could give a piece of advice to your younger self, what would it be?",
    "What you as a kid would tell yourself now?",
    "If you could go back in time and learn one thing, what would it be?",
    "What were your happiest moments?",
    "What is one work-related skill you would like to develop, particularly if it could be done easily?",
    "What new, or additional, skill do you think you need now to progress further?",
    "What do you admire most in a work colleague?",
    "Describe yourself in one word.",
    "What is the worst piece of advice you've ever received, and why was it so bad?",
    "What is one productivity tool you couldn't live without, and why is it indispensable?",
    "What is one trait you don't like the most in yourself?",
    "What is your greatest fear?",
    "Which talent would you most like to have?",
    "What do you consider your greatest achievement?",
    "What is your greatest extravagance?",
    "What do you dislike most about your appearance?",
    "What is your most treasured possession?",
    "What do you most value in your friends?",
    "What is it that you most dislike?",
    "Who are your heroes in real life?",
    "What is your favorite journey?",
    "How would you like to die?",
    "Share one boring or trivial fact about yourself.",
    "What movie are we in now, or what movie do you play in?"
  ],
  pl:[
    "Jakiego koloru są kosmici?",
    "Wolałbyś/wolałabyś cofnąć się w czasie czy przenieść do przyszłości?",
    "Kim chciałeś/chciałaś zostać, gdy byłeś/byłaś nastolatkiem?",
    "Jaka jest najlepsza rada, jaką kiedykolwiek otrzymałeś/aś?",
    "Jaka była najgorsza praca, jaką kiedykolwiek miałeś/aś?",
    "Jakiej jednej rzeczy o tobie nie wiemy?",
    "Gdybyś mógł/mogła mieszkać przez rok w dowolnym miejscu na świecie, gdzie by to było?",
    "Wolałbyś/wolałabyś być najzabawniejszą czy najmądrzejszą osobą w pokoju?",
    "Wolałbyś/wolałabyś odwiedzić wulkan czy las deszczowy?",
    "Opisz swoje wymarzone wakacje, gdyby pieniądze nie grały roli.",
    "Kiedy byłeś/aś dzieckiem, jakie było twoje największe marzenie?",
    "Jaki talent najbardziej chciałbyś/chciałabyś rozwijać?",
    "O jakich aktywnościach marzysz i chciałbyś/chciałabyś je kiedyś spróbować?",
    "Jak lubisz się ubierać (elegancko, na luzie, dres i klapki)?",
    "Masz jedną dodatkową godzinę dziennie, możesz robić co chcesz, co by to było?",
    "Jakie \"rzeczy dla starszych ludzi\" robisz?",
    "Gdybyś mógł/mogła mówić w innym języku, jaki by to był język?",
    "Czy masz listę marzeń do spełnienia? Wymień jedną rzecz z tej listy.",
    "Czego nowego lub ciekawego ostatnio się nauczyłeś/aś?",
    "Czy jest ostatnio jakiś temat, z którego chciałbyś/chciałabyś mieć mentora?",
    "Jako jakie zwierzę chciałbyś/chciałabyś się odrodzić po reinkarnacji i dlaczego?",
    "Kiedy ostatni raz zrobiłeś/aś coś po raz pierwszy?",
    "Czy kiedykolwiek przeżyłeś/aś szok kulturowy? Gdzie to było i co się stało?",
    "Czy poznałeś/aś ostatnio jakieś przydatne triki na produktywność?",
    "Jaką najodważniejszą/najbardziej ryzykowną rzecz zrobiłeś/aś lub chcesz zrobić?",
    "Co wolisz, oceany czy góry? Dlaczego?",
    "Jakich odkryć naukowych chciałbyś/chciałabyś dożyć?",
    "Czy twoje młodsze „ja” byłoby dumne z tego, kim jesteś dzisiaj?",
    "Gdybyś mógł/mogła dać radę swojemu młodszemu \"ja\", co by to było?",
    "Co jako dziecko powiedziałbyś/powiedziałabyś sobie teraz?",
    "Gdybyś mógł/mogła cofnąć się w czasie i nauczyć jednej rzeczy, co by to było?",
    "Jakie były twoje najszczęśliwsze chwile?",
    "Jaką jedną umiejętność związaną z pracą chciałbyś/chciałabyś rozwinąć, zwłaszcza gdyby to było łatwe?",
    "Jaką nową lub dodatkową umiejętność musisz zdobyć, żeby się dalej rozwijać?",
    "Co najbardziej podziwiasz u współpracownika?",
    "Opisz siebie jednym słowem.",
    "Jaka jest najgorsza rada, jaką kiedykolwiek otrzymałeś/aś, i dlaczego była taka zła?",
    "Jakie jest jedno narzędzie do produktywności, bez którego nie mógłbyś/mogłabyś żyć i dlaczego jest niezbędne?",
    "Jakiej jednej cechy najbardziej w sobie nie lubisz?",
    "Czego najbardziej się boisz?",
    "Jaki talent najbardziej chciałbyś/chciałabyś mieć?",
    "Co uważasz za swoje największe osiągnięcie?",
    "Jaka jest twoja największa ekstrawagancja?",
    "Czego najbardziej nie lubisz w swoim wyglądzie?",
    "Jaka jest twoja najcenniejsza rzecz?",
    "Co najbardziej cenisz w swoich przyjaciółach?",
    "Czego najbardziej nie lubisz?",
    "Kto jest twoim bohaterem w prawdziwym życiu?",
    "Jaka jest twoja ulubiona podróż?",
    "Jak chciałbyś/chciałabyś umrzeć?",
    "Podziel się jednym nudnym lub trywialnym faktem o sobie.",
    "W jakim filmie toczy się twoje życie lub jaką rolę w nim grasz?"
  ]
};
