var QUESTIONS={
  en:[
    "What color are aliens?",
    "Would you like to go back in time or go to the future?",
    "Who did you want to be when you were a teenager?",
    "What is the best piece of advice you've ever received?",
    "What was the worst job you ever had?",
    "What is one thing we don't know about you?",
    "If you could live anywhere in the world for a year, where would it be?",
    "Would you rather be the funniest or smartest person in the room?",
    "Would you rather visit a volcano or a rainforest?",
    "Describe your dream holiday if money was no limit.",
    "When you were a child, what was your biggest dream?",
    "What talent would you most like to grow and develop?",
    "What activities do you dream of trying someday?",
    "How do you like to dress (smart, relaxed, sweatpants and flip-flops)?",
    "You have one extra hour a day, you can do anything, what would you do?",
    "What “old person” things do you do?",
    "If you could speak another language, what would it be?",
    "Do you have a bucket list? Name one thing on your bucket list.",
    "What is something new or interesting that you've learned recently?",
    "Is there any topic lately that you find fascinating?",
    "If you were reincarnated as an animal, what would you choose and why?",
    "When was the last time you did something for the first time?",
    "Have you ever experienced a culture shock? Where was it and what happened?",
    "Have you learned any useful productivity hacks recently?",
    "What's an adventurous thing you've done or want to do?",
    "Which do you prefer, oceans or mountains? Why?",
    "What scientific discoveries would you like to live to see?",
    "Would your younger self be proud of who you are today?",
    "If you could give a piece of advice to your younger self, what would it be?",
    "What you as a kid would tell yourself now?",
    "If you could go back in time and learn one thing, what would it be?",
    "What were your happiest moments?",
    "What is one work-related skill you would like to develop, particularly if it could be done easily?",
    "What new, or additional, skill do you think you need now to progress further?",
    "What do you admire most in a work colleague?",
    "Describe yourself in one word.",
    "What is the worst piece of advice you've ever received, and why was it so bad?",
    "What is one tool you couldn't live without, and why is it indispensable?",
    "What is one trait you don't like the most in yourself?",
    "What is your greatest fear?",
    "Which talent would you most like to have?",
    "What do you consider your greatest achievement?",
    "What is your greatest extravagance?",
    "What do you dislike most about your appearance?",
    "What is your most treasured possession?",
    "What do you most value in your friends?",
    "What superpower would you like to have?",
    "Who are your heroes in real life?",
    "What is your favorite journey?",
    "How would you like to die?",
    "Share one boring or trivial fact about yourself.",
    "What movie are we in now, or what movie do you play in?"
  ],
  pl:[
    "Jakiego koloru są kosmici?",
    "Wolałbyś/ wolałabyś przenieść się do przeszłości, czy raczej do przyszłości?",
    "Jaką ścieżkę kariery widziałeś/widziałaś dla siebie w wieku 16 lat?",
    "Podziel się najlepszą radą, jaką kiedykolwiek otrzymałeś/aś.",
    "Jaka była Twoja najgorsza praca i dlaczego?",
    "Jakiej jednej rzeczy o Tobie nie wiemy?",
    "Gdybyś mógł/mogła mieszkać przez rok w dowolnym miejscu na świecie, gdzie by to było?",
    "Wolałbyś/wolałabyś być najzabawniejszą czy najmądrzejszą osobą w grupie?",
    "Wejście na wulkan czy spacer po lesie deszczowym?",
    "Gdyby pieniądze nie grały roli, gdzie chciałbyś/chciałabyś spędzić wakacje?",
    "O czym najbardziej marzyłeś/marzyłaś w wieku 6-8 lat?",
    "Jaki talent najbardziej chciałbyś/chciałabyś zdobyć lub rozwinąć?",
    "Jakich aktywności chciałbyś/chciałabyś kiedyś spróbować?",
    "Jak lubisz się ubierać (elegancko, na luzie, a może kapcie i dres)?",
    "Gdyby dzień miał dodatkową godzinę, którą możesz spędzić w dowolny sposób, jak byś ją zagospodarował/a?",
    "Czy masz jakieś boomerskie zwyczaje?",
    "Jaki dodatkowy język chciałbyś/chciałabyś znać?",
    "Wymień jedną rzecz ze swojej listy marzeń i celów.",
    "Czego nowego lub ciekawego ostatnio się nauczyłeś/aś?",
    "Czy coś Cię ostatnio szczególnie zafascynowało?", 
    "Załóżmy, że reinkarnacja istnieje. Jako jakie zwierzę chciałbyś/ chciałabyś się odrodzić i dlaczego?",
    "Kiedy ostatni raz zrobiłeś/aś coś po raz pierwszy?",
    "Czy kiedykolwiek przeżyłeś/aś szok kulturowy? Jeśli tak, to w jakiej sytuacji?",
    "Czy poznałeś/aś ostatnio jakieś przydatne triki na zwiększenie produktywności?",
    "Jaką najodważniejszą czy też najbardziej ryzykowną rzecz zrobiłeś/aś albo chcesz zrobić?",
    "Morza/oceany czy góry? Uzasadnij wybór.",
    "Na jakie odkrycia naukowe najbardziej czekasz?",
    "Czy Twoje młodsze „ja” byłoby dumne z tego, kim jesteś dzisiaj?",
    "Gdybyś mógł/mogła dać radę swojemu młodszemu \"ja\", co by to było?",
    "Co jako dziecko powiedziałbyś/powiedziałabyś sobie teraz?",
    "Gdybyś mógł/mogła cofnąć się w czasie i nauczyć jednej rzeczy, co by to było?",
    "Jakie były twoje najszczęśliwsze chwile?",
    "Jaką jedną umiejętność związaną z pracą chciałbyś/chciałabyś rozwinąć, zwłaszcza gdyby to było łatwe?",
    "Jaką nową lub dodatkową umiejętność musisz zdobyć, żeby się dalej rozwijać?",
    "Co najbardziej podziwiasz u współpracowników?",
    "Opisz siebie jednym słowem.",
    "Jaka jest najgorsza rada, jaką kiedykolwiek otrzymałeś/aś, i dlaczego była taka zła?",
    "Jakie jest jedno narzędzie bez którego nie mógłbyś/ mogłabyś żyć i dlaczego jest niezbędne?",
    "Jakiej jednej cechy najbardziej w sobie nie lubisz?",
    "Czego najbardziej się boisz?",
    "Jaki talent najbardziej chciałbyś/chciałabyś mieć?",
    "Co uważasz za swoje największe osiągnięcie?",
    "Jaka jest twoja największa ekstrawagancja?",
    "Czego najbardziej nie lubisz w swoim wyglądzie?",
    "Jaka jest twoja najcenniejsza rzecz?",
    "Co najbardziej cenisz w swoich przyjaciółach?",
    "Jaką supermoc chciałbyś/chciałabyś mieć?",
    "Kto jest twoim bohaterem w prawdziwym życiu?",
    "Jaka jest twoja ulubiona podróż?",
    "Jak chciałbyś/chciałabyś umrzeć?",
    "Podziel się jednym nudnym lub trywialnym faktem o sobie.",
    "W jakim filmie toczy się twoje życie i jaką rolę w nim grasz?"
  ]
};

var DOOM_QUESTIONS={
  en:[
    "You have 24 hours left to live. What are 3 things you do?",
    "If you were forced to become someone else, who would you rather be?",
    "The Earth explodes in 8 hours. What do people do?",
    "What would you want the last sentence of your obituary to say?",
    "You can know the exact date of your death. Do you want to? Why?",
    "Which of your memories would hurt the most to lose?",
    "What would your enemies say at your funeral?",
    "Humanity gets one final message before the end. What should it say?",
    "Would you rather forget everyone you love, or be forgotten by them?",
    "What decision do you fear you'll regret on your deathbed?",
    "The world ends tomorrow. What do you finally confess, and to whom?",
    "If your life so far had a warning label, what would it say?",
    "Which version of you died so this one could exist?",
    "What do you own that should be burned when you die?",
    "If you had to disappear and start over with nothing, where would you go?",
    "Everyone forgets you ever existed, but you get to keep one impact you made. Which one?",
    "You're the last person on Earth. What's your daily routine?"
  ],
  pl:[
    "Zostały ci 24 godziny życia. Jakie 3 rzeczy robisz?",
    "Gdyby zmuszono cię do bycia kimś innym, kim wolisz zostać?",
    "Ziemia wybuchnie za 8 godzin. Co robią ludzie?",
    "Jak ma brzmieć ostatnie zdanie twojego nekrologu?",
    "Możesz poznać dokładną datę swojej śmierci. Chcesz? Dlaczego?",
    "Utrata którego wspomnienia zabolałaby cię najbardziej?",
    "Co powiedzieliby twoi wrogowie na twoim pogrzebie?",
    "Ludzkość dostaje jedną ostatnią wiadomość przed końcem. Co powinna mówić?",
    "Wolisz zapomnieć wszystkich, których kochasz, czy zostać przez nich zapomniany?",
    "Której decyzji – jak się obawiasz – będziesz żałować na łożu śmierci?",
    "Jutro koniec świata. Co w końcu wyznajesz i komu?",
    "Gdyby twoje dotychczasowe życie miało etykietę ostrzegawczą, co by na niej było?",
    "Która wersja ciebie musiała umrzeć, żeby mogła istnieć ta?",
    "Co posiadasz, co powinno spłonąć po twojej śmierci?",
    "Gdybyś musiał zniknąć i zacząć od zera bez niczego, dokąd byś pojechał?",
    "Wszyscy zapominają, że istniałeś, ale możesz zachować jeden ślad, który zostawiłeś. Który?",
    "Jesteś ostatnią osobą na Ziemi. Jak wygląda twój dzień?"
  ]
};
